hslavich_onelogin_saml:
    idp:
        entityId: "%env(SAML_ENTITY_ID)%"
        singleSignOnService:
            url: "%env(SAML_SINGLE_LOGIN_SERVICE_URL)%"
            binding: "%env(SAML_SINGLE_LOGIN_SERVICE_BINDING)%"
        singleLogoutService:
            url: "%env(SAML_SINGLE_LOGOUT_SERVICE_URL)%"
            binding: "%env(SAML_SINGLE_LOGOUT_SERVICE_BINDING)%"
        x509cert: "%env(SAML_APP_CERT)%"
    sp:
        entityId: "%env(BACKEND_BASE_URL)%/saml/metadata"
        assertionConsumerService:
            url: "%env(BACKEND_BASE_URL)%/saml/acs"
            binding: "%env(SAML_ACS_BINDING)%"
        singleLogoutService:
            url: "%env(BACKEND_BASE_URL)%/saml/logout"
            binding: "%env(SAML_SP_SINGLE_LOGOUT_SERVICE_BINDING)%"
