version: "3.8"
services:
  database:
    image: postgres
    container_name: db_saml_tuto
    restart: always
    volumes:
      - db-data:/var/lib/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    networks:
      - dev
  adminer:
    image: adminer
    container_name: db_saml_tuto_adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - dev
  www:
    build: docker/php
    container_name: www_saml_tuto
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
networks:
  dev:

volumes:
  db-data: