version: "3.8"
services:
  db:
    image: postgres
    container_name: db_saml_tuto
    restart: always
    volumes:
      - db-data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - dev
  adminer:
    image: adminer
    container_name: db_saml_tuto_adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - dev
networks:
  dev:

volumes:
  db-data: